repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: autopep8-wrapper
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: flake8
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
